### ISSUE TITLE
Minor tweaks needed for Linux port

### ISSUE THREAD

**Issue by rrooij** [AdmiralCurtiss/ToVPatcher#1]
A GNU/Linux port would be nice. The application runs in Mono and can already patch the PARAM.SFO on Linux. Some minor errors prevent the other files from being patched (path directory differences, which are easy to solve). Xdelta is also available to install on most Linux distributions.

The only major obstacle is the ebootmod now. But it can not be legally provided with the patcher anyway and it would be nice to get the other patches working at least.

I would like to add support for this. I'd like to ask your opinion of this before developing it. Maybe I'm missing some more Windows exclusive tools that I haven't covered in this issue.

**Comment by AdmiralCurtiss** [comment]
If you want to add Linux support for this, go ahead! I think the only real issues here are the native programs called, which in addition to the `xdelta` and `ebootmod` you identified includes `comptoe` for the old Tales-specific file compression still used in a handful of Vesperia's files. The source of this program can be found here, so you can probably just compile a Linux version of it: https://github.com/talestra/talestra/tree/master/compto. Or if you're super motivated, port it to C#!

You may also have to pay attention to filesystem stuff, I don't know if I paid a lot of attention to case-sensitivity of filenames. Also, the checksums expect the files to be packed in the archive in a specific order, so pay attention to that too.

**Comment by rrooij** [comment]
@AdmiralCurtiss I made some progress and I'm curious about your thoughts.

There was one case-sensitive error that I fixed in a pull request already.

Would you mind me to replace the animated gif for loading with a static hourglass icon or another loading indicator? Mono crashes on animated gifs in WinForm applications specifically due to a bug.

Another minor fix that I would like to discuss is renaming the xdelta executable and call to xdelta3. xdelta and xdelta3 both exist in most Linux distributions, but this program uses xdelta3 specifically.

See: https://linux.die.net/man/1/xdelta and https://www.systutorials.com/docs/linux/man/1-xdelta3/ , they are both separate programs. So by default it calls the wrong xdelta in most Linux distributions (the old one, not xdelta3).

`btl.svo` is already succesfully patched in Linux with your tool and these modifications. chara.svo fails due to a wrong MD5, this could be because of the package order you mentioned earlier, but I have to look into that further.

**Comment by AdmiralCurtiss** [comment]
That all seems fine to me.

**Comment by rrooij** [comment]
@AdmiralCurtiss, what do you think about using the failoverfl0w PS3 tools for decrypting and encrypting the EBOOT.DAT only on Mac OS X and Linux (unself and makeself)? It is pretty straightforward where the keys are stored, that is in the `~/.ps3` directory.  We could use it for Windows too but from what I've heard it is hard to know where it searches for keys and may be not so straightforward for users to install, as the keys are not stored in the binary itself like ebootMOD.

The upside is that we can ship unself and makeself legally with the program as long as we don't provide the keys with it.

Update: I see that it searches for keys in the environment variable SONY_KEYS and in the ~/.ps3 folder. Should be pretty easy to set and instruct users to place the keys in a directory inside the application folder.

**Comment by AdmiralCurtiss** [comment]
Guess this can be closed now, too, with #3 merged.

**Comment by rrooij** [comment]
Yeah, thanks so much for your cooperation. And maybe we will find a replacement for fself in the future.
